// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awvoapgacxsyrjtmsjsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3dm9hcGdhY3hzeXJqdG1zanN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTI5NjcsImV4cCI6MjA3Mzc2ODk2N30.OTEQX00hB_VjfkfZApx_IxdNJJ-iwd92nSvo3ekFM6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});